#!/bin/sh
python find_similar_images_with_distribution.py \
--dict_mode SAVE \
--dataset_name sample_fall11_urls_t30 \
--sort_method default \
--similarity_method Cosine \
--find_indecisives True \
--find_similars True \
python find_similar_images_with_distribution.py \
--dict_mode RESTORE \
--dataset_name sample_fall11_urls_t30 \
--sort_method weighted \
--similarity_method Cosine \
--find_indecisives True \
--find_similars False \
python find_similar_images_with_distribution.py \
--dict_mode RESTORE \
--dataset_name sample_fall11_urls_t30 \
--sort_method default \
--similarity_method Cosine \
--find_indecisives False \
--find_similars True \
python find_similar_images_with_distribution.py \
--dict_mode RESTORE \
--dataset_name sample_fall11_urls_t30 \
--sort_method default \
--similarity_method KL \
--find_indecisives False \
--find_similars True \
